version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
      - echo "Code Scanning..."
      - mvn clean verify sonar:sonar
      - pwd
      - ls -lrt
      - ls -lrta /root/.m2/
      - cp -pvr settings.xml /root/.m2/
      - ls -lrta /root/.m2/
      - echo "Code Scanning has been completed!"

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean validate compile test install verify package
      - ls -lrta
      - apt update
      - apt install curl -y
      - apt-get install -y jq
      - echo "Checking SonarQube quality gate status..."
      - |
        QUALITY_GATE_STATUS=$(curl -s -u sqp_831f1c44c9b977596a5b05e85d6e305986874074: "http://54.89.137.66:9000/api/qualitygates/project_status?projectKey=Capstone" | jq -r .projectStatus.status)
        if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
          echo "Quality gate failed. Aborting deployment."
          exit 1
        fi
      - echo "Quality gate passed. Proceeding to deploy to Tomcat."
      - echo "Uploading WAR file to S3"
      - aws s3 cp target/*.war s3://raazproject/Capstone/
      - echo "Deploying WAR file to Tomcat"
      - curl -u admin:Rajesh@123 -T target/**.war "http://54.225.11.152:8080/manager/text/deploy?path=/capstoneapp&update=true"
  post_build:
    commands:
      - echo "Build complete on $(date)"

artifacts:
  files:
    - '**/*'
